import Link from "next/link";
import { History, MessageCircle, ShoppingBag } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { Card,CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { OrderForm } from "@/components/dashboard/order-form";
import { loadCatalog } from "@/lib/catalog";
import type { Order } from "@/types/database";
const one=(v:string|string[]|undefined)=>typeof v==="string"?v:undefined;
export default async function Dashboard({searchParams}:{searchParams:Promise<{order?:string|string[];variant?:string|string[]}>}){const sp=await searchParams;const {supabase,user,profile}=await requireUser();const [cat,last]=await Promise.all([loadCatalog(supabase,{onlyActive:true}),supabase.from("orders").select("*").eq("user_id",user.id).order("created_at",{ascending:false}).limit(1).maybeSingle()]);const recent=last.data as Order|null;return <main className="page"><div className="shell max-w-3xl"><div className="mb-7 flex items-start justify-between gap-4"><div className="min-w-0"><p className="text-sm text-zinc-500">Dashboard</p><h1 className="mt-1 break-words text-2xl font-bold tracking-tight">Hai, {profile?.username||"User"}</h1><p className="mt-1 text-sm text-zinc-500">Order layanan dan pantau prosesnya di sini.</p></div><div className="flex shrink-0 gap-2"><Button asChild variant="outline" size="icon"><Link href="/dashboard/history" aria-label="Riwayat transaksi"><History className="size-4"/></Link></Button><Button asChild variant="outline" size="icon"><Link href="/dashboard/chat" aria-label="Chat admin"><MessageCircle className="size-4"/></Link></Button></div></div>{recent&&<Link href="/dashboard/history" aria-label="Lihat riwayat transaksi" className="mb-4 block rounded-2xl transition active:scale-[.99]"><Card className="transition hover:border-zinc-700"><CardContent className="flex items-center gap-4 py-4"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-zinc-900 text-emerald-400"><ShoppingBag className="size-5"/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{recent.product}</p><p className="mt-0.5 text-xs text-zinc-500">Order terakhir</p></div><span className="shrink-0 rounded-full border border-zinc-800 bg-zinc-900 px-2.5 py-1 text-xs font-medium text-zinc-300">{recent.status}</span></CardContent></Card></Link>}<Card><OrderForm userId={user.id} groups={cat.groups} variants={cat.variants} initialKey={one(sp.order)} initialVariant={one(sp.variant)}/></Card></div></main>}
