import Link from "next/link";
import { History, MessageCircle, ShoppingBag } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { OrderForm } from "@/components/dashboard/order-form";
import { loadCatalog } from "@/lib/catalog";
import type { Order } from "@/types/database";
type Search={order?:string|string[];variant?:string|string[]};
const first=(v?:string|string[])=>Array.isArray(v)?v[0]:v;
export default async function Dashboard({searchParams}:{searchParams:Promise<Search>}){const sp=await searchParams;const {supabase,user,profile}=await requireUser();const [cat,last]=await Promise.all([loadCatalog(supabase,{onlyActive:true}),supabase.from("orders").select("*").eq("user_id",user.id).order("created_at",{ascending:false}).limit(1).maybeSingle()]);if(last.error)console.error("[dashboard] gagal memuat order terakhir",{code:last.error.code,message:last.error.message});const recent=last.data as Order|null;return <main className="page"><div className="shell max-w-3xl"><div className="mb-7 flex items-start justify-between gap-4"><div><p className="text-sm text-zinc-500">Dashboard</p><h1 className="mt-1 text-2xl font-bold tracking-tight">Hai, {profile?.username||"User"}</h1><p className="mt-1 text-sm text-zinc-500">Order layanan dan pantau prosesnya di sini.</p></div><div className="flex shrink-0 gap-2"><Button asChild variant="outline" size="icon"><Link href="/dashboard/history" aria-label="Riwayat transaksi"><History className="size-4"/></Link></Button><Button asChild variant="outline" size="icon"><Link href="/dashboard/chat" aria-label="Chat admin"><MessageCircle className="size-4"/></Link></Button></div></div>{recent&&<Card className="mb-4"><CardContent className="flex items-center gap-4 py-4"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-zinc-900 text-emerald-400"><ShoppingBag className="size-5"/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{recent.product}</p><p className="mt-0.5 text-xs text-zinc-500">Order terakhir</p></div><span className="rounded-full border border-zinc-800 bg-zinc-900 px-2.5 py-1 text-xs font-medium text-zinc-300">{recent.status}</span></CardContent></Card>}<Card><CardHeader><p className="text-xs font-semibold uppercase tracking-wider text-emerald-400">Order</p><CardTitle className="text-xl">Buat order baru</CardTitle></CardHeader><CardContent>{cat.status==="query_error"||cat.status==="env_missing"?<p role="alert" className="text-sm text-red-400">Katalog sedang tidak dapat dimuat. Coba lagi beberapa saat lagi.</p>:<OrderForm userId={user.id} groups={cat.groups} variants={cat.variants} initialKey={first(sp.order)} initialVariant={first(sp.variant)}/>}</CardContent></Card></div></main>}
