import { notFound } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Star } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { Card,CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { rupiah } from "@/lib/utils";
import type { CatalogGroup,CatalogVariant,Review } from "@/types/database";
export default async function ProductPage({params}:{params:Promise<{key:string}>}){const {key}=await params;const s=await createClient();const [g,v,r]=await Promise.all([s.from("product_catalog_groups").select("*").eq("product_key",key).eq("archived",false).maybeSingle(),s.from("product_catalog").select("*").eq("product_key",key).eq("active",true).eq("archived",false).order("sort"),s.from("reviews").select("*").eq("product_key",key).order("created_at",{ascending:false}).limit(5)]);if(!g.data)notFound();const group=g.data as CatalogGroup,variants=(v.data||[]) as CatalogVariant[],reviews=(r.data||[]) as Review[];const avg=reviews.length?reviews.reduce((n,x)=>n+x.rating,0)/reviews.length:0;return <main className="page"><div className="shell max-w-4xl"><Link href="/" className="inline-flex items-center gap-2 text-sm text-zinc-500 transition hover:text-white"><ArrowLeft className="size-4"/>Katalog</Link><div className="mt-7 grid gap-8 lg:grid-cols-[1fr_1.15fr]"><section><p className="text-sm font-semibold text-emerald-400">Digital product</p><h1 className="mt-2 text-4xl font-black tracking-tight">{group.name}</h1><p className="mt-4 leading-7 text-zinc-400">{group.description}</p>{reviews.length>0&&<div className="mt-6 flex items-center gap-2 text-sm"><Star className="size-4 fill-amber-400 text-amber-400"/><b>{avg.toFixed(1)}</b><span className="text-zinc-500">dari ulasan terbaru</span></div>}</section><section className="grid gap-3">{variants.map(x=><Card key={x.variant_id} className="transition hover:border-zinc-700"><CardContent className="flex items-center justify-between gap-5 py-5"><div><p className="font-semibold">{x.label}</p><p className="mt-1 text-lg font-bold text-emerald-400">{rupiah(x.price)}</p></div><Button asChild><Link href={`/dashboard?order=${key}&variant=${x.variant_id}`}>Order <ArrowRight className="size-4"/></Link></Button></CardContent></Card>)}{!variants.length&&<p className="text-sm text-zinc-500">Belum ada varian aktif.</p>}</section></div><section className="mt-14 border-t border-zinc-900 pt-8"><h2 className="text-xl font-bold">Ulasan terbaru</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{reviews.map(x=><Card key={x.id}><CardContent className="pt-5"><div className="flex items-center justify-between gap-3"><b className="text-sm">{x.username}</b><span className="text-sm text-amber-400">{"★".repeat(x.rating)}</span></div><p className="mt-3 text-sm leading-6 text-zinc-400">{x.comment||"Tanpa komentar"}</p></CardContent></Card>)}{!reviews.length&&<p className="text-sm text-zinc-500">Belum ada ulasan.</p>}</div></section></div></main>}
